FROM golang:1.24-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod tidy

# Copy the source code
COPY . .

# Build the application
RUN go build -o main ./cmd/api

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["./main"]
